language: go
before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
go:
  - 1.7
  - 1.7.1
  - 1.7.2
  - 1.7.3
  - 1.7.4
  - 1.7.5
  - 1.7.6
  - 1.8
  - 1.8.1
  - 1.8.2
  - 1.8.3
  - tip
script:
  - make test
  - make lint
services:
  - redis-server
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
